# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'PaltaExample' do
  use_frameworks!
  
  # Palta SDKs
  pod 'PaltaLibAnalytics', '~> 2.1.6'
  pod 'PaltaLibPurchases', '3.0.0'
  
  # Helper libraries
  pod 'SnapKit'
  pod 'MBProgressHUD', '~> 1.2.0'

end
