# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'PaltaExample' do
  use_frameworks!
  
  # Palta SDKs
  pod 'PaltaLibEvents', '1.0.2'
  pod 'PaltaLibPurchases', '3.0.0'
  
  # Helper libraries
  pod 'SnapKit'

end
