# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'PaltaExample' do
  use_frameworks!

  pod 'PaltaLibAnalytics', '~> 2.1.5'
  pod 'PaltaLibPurchases', :git => 'https://github.com/Palta-Data-Platform/paltalib-ios.git', :branch => 'develop'
  pod 'PaltaLibCore', :git => 'https://github.com/Palta-Data-Platform/paltalib-ios.git', :branch => 'develop'

end
