name: Push podspec
on:
  workflow_dispatch:
    inputs:
      component:
        type: choice
        description: Which podspec to push
        options:
          - Core
          - Analytics
          - Attribution
          - Purchases
    
jobs:
  build:
    runs-on: [ macos-12 ]
    steps:
    - uses: actions/checkout@v1
    - name: Publish to CocoaPod register
      env:
        COCOAPODS_TRUNK_TOKEN: ${{ secrets.COCOAPODS_TRUNK_TOKEN }}
      run: |
        pod trunk push PaltaLib${{ github.event.inputs.component }}.podspec --allow-warnings
