name: Run tests
on:
  workflow_dispatch:
  push:
    branches:
      - develop
      - main
      - release/**
  
    
jobs:
  build:
    runs-on: macos-12
    steps:
    - uses: actions/checkout@v1
    - name: Select Xcode
      run: sudo xcode-select -switch /Applications/Xcode_13.2.1.app && /usr/bin/xcodebuild -version
    - name: Run unit tests
      run: |
        xcodebuild test -project PaltaLib.xcodeproj \
            -scheme PaltaLibTests \
            -sdk iphonesimulator \
            -destination 'platform=iOS Simulator,name=iPhone 12,OS=15.2' \
            | xcpretty && exit ${PIPESTATUS[0]}

